# 0 Sources
#  Copper vein (CV)
#  Iron vein (IV)
#  Stone vein (SV)
#   Silicon vein (SiV)
#       Fractal silicon vein (FSiV)
#       Star (ST)
#       Crude oil vein (CoilV)
#       Ice giant (ICE)
#       Fire ice vein (FIV)
#       Coal vein (CLV)
#       Gas giant (GAS)
#       Optical grating rock vein (OPRV)
#       Titanium vein (TiV)
#       Sulfur sea (SS)
#       Water sea (WS)
#       Organic crystal vein (OCV)
#       Kimberlite vein (KiV)
#   Spiniform stalagmite crystal vein (SpSCV)
#  * Level one
#   Copper ore (Cor)
#   Iron ore (Ior)
#   Stone (Stn)
#   Silicon ore (Sir)
#   Fractal silicon (FS)
#   Unipolar magnet (UM)
#   Crude oil (Coil)
#   Fire ice (FI)
#   Coal (CL)
#   Optical grating crystal  (OGC)
#   Titanium ore (TiO)
#   Water (H20)
#   Plant fuel (PF)
#   Log (L)
#   Kimberlite ore (Ki)
#   Spiniform stalagmite crystal (SpSC)
# ** Level two
#   Iron ingot (IIn)
#   Copper ingot (CIn)
#   High-purity silicon (HPSi)
#   Stone brick (SBr)
#   Glass (Gl)
#   Steel (STL)
#   Magnet  (Mag)
#   Prism (Psm)
#   Crystal silicon (CrySi)
#   Critical photon (CriPh)
#   Refined oil (Roil)
#   Hydrogen (H)
#   Energetic graphite  (EGr)
#   Graphene  (Grph)
#   Deuterium (Deut)
#   Titanium ingot  (TiIn)
#   Sulfuric acid  (SA)
#   Strange matter  (SM)
#   Plastic (Plst)
#   Titanium glass  (TiGl)
#   Organic crystal  (OrCry)
#   Titanium crystal  (TiCry)
#   Casimir crystal (CaCry)
#   Diamond  (Dia)
#   Carbon nanotube  (CaNano)
#   Antimatter  (Anti)
#   Titanium alloy  (TiAll)
#   Frame material (Fram)
# *** Level three
#   Electromagnetic matrix  (ElMa)
#   Energy matrix  (EnMa)
#   Solar sail  (Solar)
#   Hydrogen fuel rod  (HyFR)
#   Information matrix (IM)
#   Deuteron fuel rod (DeutFR)
#   Structure matrix  (SMa)
#   Gravity matrix (GMa)
#   Universe matrix (MMa)
#   Small carrier rocket (SCR)
#  Antimatter fuel rod (AntiFR)
#  *** LEvel four
#   Gear  (GR)
#   Magnetic coil (MagCoil)
#   Circuit board   (PCB)
#   Electric motor   (EM)
#   Microcrystalline component  (MICRO)
#   Thruster (THR)
#   Electromagnetic turbine  (EMT)
#   Foundation  (FDT)
#   Plasma exciter (PLE)
#   Photon combiner (PHCB)
#   Particle container (ParCT)
#   Processor (Proc)
#   Super-magnetic ring (SMagR)
#   Particle broadband (PartBB)
#   Plane filter (PlnF)
#   Graviton lens  (GravLn)
#   Dyson sphere component  (DSC)
#   Space warper  (SpW)
#   Quantum chip  (QCh)  
#   Annihilation constraint sphere  (ACS)
#   Reinforced thruster  (ReT)
# **** Level five
#   Wind turbine  (WTur)
#   Assembling machine Mk.I  (AMkI)
#   Mining machine (Mine)
#   Tesla tower (Tesla)
#   Thermal power plant (TPP)
#   Solar panel (SolPP)
#   Matrix lab  (MatLab)
#   Arc Smelter (ArcSmel)
#   Water pump (WPp)
#   Chemical plant (ChPl)
#   Oil extractor  (OilX)
#   Oil refinery    (OilR)
#   Wireless power tower  (WPT)
#   Fractionator  (Frac)
#   EM-Rail Ejector  (EmRailEj)
#   Accumulator  (Accum)
#   Ray receiver  (Ray)
#   Energy exchanger  (EnEx)
#   Assembling machine Mk.II  (AMkII)
#   Miniature particle collider  (MPC)
#   Mini fusion power plant  (MiniFPP)
#   Satellite substation  (SatSub)
#   Assembling machine Mk.III  (AMkIII)
#   Plane Smelter  (PlaneSm)
#   Vertical launching silo (VertSilo)
#   Accumulator (full)  (AccumF)
#   Artifical star  (ArtStr)
#  *****    Level six
#   Splitter (Split)
#   Conveyer belt MK.I  (CBMkI)
#   Sorter MK.I  (SortMkI)
#   Sorter MK.II  (SortMkII)
#   Storage MK.I (StoreMkI)
#   Logistics drone  (LogDrn)
#   Storage tank  (StrTnk)
#   Sorter MK.III  (SortMkII)
#   Conveyor belt MK.II  (CBMkII)
#   Storage MK.II  (StoreMkII)
#   Conveyor belt MK.III  (CBMkIII)
#   Planetory Logistics Station  (PlaLog)
#   Interstellar Logistics Station  (InterLog)
#   Orbital Collector   (OrbClct)
#   Logistics vessel    (LogVes)
#   ITEMS: 136
  